export enum StatCategory {
  AST = "AST",
  BLK = "BLK",
  DREB = "DREB",
  EFF = "EFF",
  FG3A = "FG3A",
  FG3M = "FG3M",
  FG3PCT = "FG3PCT",
  FGA = "FGA",
  FGM = "FGM",
  FG_PCT = "FG_PCT",
  FTA = "FTA",
  FTM = "FTM",
  FT_PCT = "FT_PCT",
  GP = "GP",
  MIN = "MIN",
  OREB = "OREB",
  PTS = "PTS",
  REB = "REB",
  STL = "STL",
  TOV = "TOV",
}
