export enum StatCat {
  AST = "AST",
  BLK = "BLK",
  DREB = "DREB",
  EFF = "EFF",
  FG3A = "FG3A",
  FG3M = "FG3M",
  FG3_PCT = "FG3_PCT",
  FGA = "FGA",
  FGM = "FGM",
  FG_PCT = "FG_PCT",
  FTA = "FTA",
  FTM = "FTM",
  FT_PCT = "FT_PCT",
  GP = "GP",
  MIN = "MIN",
  OREB = "OREB",
  PTS = "PTS",
  REB = "REB",
  STL = "STL",
  TOV = "TOV",
}

export enum StatPerMode {
  MINUTES_PER = "MinutesPer",
  PER_100_PLAYS = "Per100Plays",
  PER_100_POSSESSIONS = "Per100Possessions",
  PER36 = "Per36",
  PER40 = "Per40",
  PER48 = "Per48",
  PER_GAME = "PerGame",
  PER_MIN = "PerMinute",
  PER_PLAY = "PerPlay",
  PER_POSSESSION = "PerPossession",
  TOTALS = "Totals",
}
